### ISSUE TITLE
I have 4 websites monitored but only 1 is shown

### ISSUE THREAD

**Issue by anapaulagomes** [nya1/updown-status-page#8]
Hey! First, thanks for coming up with this project. It's really cool!
I have a problem: 4 websites have been monitored in my updown account but only one is shown on my page: https://dadosabertosdefeira-monitoramento.netlify.com/. Do you have any idea about the reason? Thanks!

**Comment by nya1** [comment]
Hello,
Private checks are not displayed, to make it public go to your updown page check and set the public page on the top.

**Comment by anapaulagomes** [comment]
Problem solved! Thanks! 🌷
